### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/COMPASS#100]
## COMPASS
* [ ] SSL Cert Installed (certbot)
* [ ] https works
* [ ] intended URL works
* [ ] migrate final data if needed

## OCS
* [ ] SSL Cert Installed (certbot)
* [ ] https works
* [ ] intended URL works
* [ ] migrate and test final data
   * [ ] purge any fixed-protocol records

**Comment by rhodges** [comment]
Once the DNS updates have been made, do the following:
```
sudo certbot --nginx -d dev.compass.dfw.state.or.us
sudo certbot --nginx -d compass.dfw.state.or.us
sudo certbot --nginx -d oregonconservationstrategy.org
```

**Comment by rhodges** [comment]
Dump commands:
## COMPASS
```
sudo su postgres
pg_dump compass > /tmp/compass_dump_$(date +%F).sql
pg_dump compass_dev > /tmp/compass_dev_dump_$(date +%F).sql
exit
 mysqldump -u ocs_user -p ocs_wp > /tmp/ocs_dump-$(date +%F).sql
```

**Comment by rhodges** [comment]
Determine intended compass(/_dev) DB user and insert for "USERNAME" below.
You should also know the mysql db password
replace references to `./` below with the location where you copied the dumps to on the target server.
load commands:
```
sudo su postgres
dropdb compass
createdb -O USERNAME compass 
psql compass < ./compass_dump_YYYY-MM-DD.sql
dropdb compass_dev
createdb -O USERNAME compass_dev
psql compass_dev < ./compass_dev_dump_YYYY-MM-DD.sql
exit
dj migrate --fake-initial
djdev migrate --fake-initial
mysql -u ocs_user -p ocs_wp < ./ocs_dump-YYYY-MM-DD.sql
```

**Comment by rhodges** [comment]
1. [ ] ODFW confirms that their data on Staging is up to date
2. [ ] Ecotrust migrates data to production
3. [ ] ODFW verifies that data on Production looks appropriate
4. [ ] ODFW ISD updates DNS records for OCS and Compass Prod on a FRIDAY EVENING
5. [ ] Ecotrust installs SSL over the weekend once DNS records have propagated
6. [ ] Ecotrust tests OCS & Compass via HTTPS
7. [ ] ODFW test OCS & Compass via HTTPS
8. [ ] ODFW reviews all external links to OCS and Compass for consistency
   * HTTP links should still work, will redirect to HTTPS.
9. [ ] Celebrate
